# Generated by Django 4.2.3 on 2023-08-10 20:32

import SportClubSofia.sport_club_app.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_club_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skater',
            name='name',
        ),
        migrations.AddField(
            model_name='skater',
            name='first_name',
            field=models.CharField(default=1, max_length=20, validators=[django.core.validators.MinLengthValidator(2), SportClubSofia.sport_club_app.validators.check_string_only_letters, SportClubSofia.sport_club_app.validators.check_for_capital_first_letter]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skater',
            name='last_name',
            field=models.CharField(default=1, max_length=20, validators=[django.core.validators.MinLengthValidator(2), SportClubSofia.sport_club_app.validators.check_string_only_letters, SportClubSofia.sport_club_app.validators.check_for_capital_first_letter]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos', validators=[SportClubSofia.sport_club_app.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='skater',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos', validators=[SportClubSofia.sport_club_app.validators.validate_file_size]),
        ),
    ]
