# Generated by Django 4.2.3 on 2023-07-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport_club_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubuser',
            name='profile_picture',
        ),
    ]
