# Generated by Django 4.2.3 on 2023-07-26 19:36

import SportClubSofia.sport_club_app.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport_club_app', '0002_remove_clubuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CHICKS', 'Chicks'), ('CUBS', 'Cubs'), ('BASIC NOVICES', 'Basic Novices'), ('INTERMEDIATE NOVICES', 'Intermediate Novices'), ('ADVANCED NOVICES', 'Adverted Novices'), ('JUNIOR', 'Junior'), ('SENIOR', 'Senior')], max_length=35)),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), SportClubSofia.sport_club_app.validators.check_string_only_letters])),
                ('image_url', models.URLField(verbose_name='Image URL')),
                ('age', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
