# Generated by Django 4.2.3 on 2023-08-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_club_app', '0002_remove_skater_name_skater_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='location',
            new_name='location_city',
        ),
        migrations.AddField(
            model_name='competition',
            name='location_country',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
