# Generated by Django 4.2.3 on 2023-08-10 21:16

import SportClubSofia.sport_club_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_club_app', '0003_rename_location_competition_location_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='photos', validators=[SportClubSofia.sport_club_app.validators.validate_file_size]),
        ),
    ]
