# Generated by Django 4.2.3 on 2023-07-29 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport_club_app', '0003_skater'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skater',
            old_name='user',
            new_name='coach',
        ),
    ]
